trigger:
  branches:
    include:
      - main  # Trigger pipeline on the 'main' branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '16.x'

steps:
# Step 1: Manually Install Java 17
- script: |
    echo "Installing Java 17"
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk
    java -version
  displayName: 'Install and set up Java 17 manually'

# Step 2: Verify Java Version
- script: |
    echo "Verifying Java version"
    java -version
  displayName: 'Verify Java Version'

# Step 3: Build the backend (Spring Boot)
- script: |
    echo "Making Maven Wrapper executable"
    cd backend
    chmod +x mvnw  # Fix permission issue for mvnw
    echo "Setting JAVA_HOME"
    export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    export PATH=$JAVA_HOME/bin:$PATH
    echo "Building Spring Boot backend"
    ./mvnw clean package
  displayName: 'Build backend with Maven'

# Step 4: Publish backend artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'backend/target/*.jar'
    artifactName: 'backend'
  displayName: 'Publish backend artifact'

# Step 5: Set up Node.js for the frontend
- task: NodeTool@0
  inputs:
    versionSpec: '$(NODE_VERSION)'
  displayName: 'Set up Node.js $(NODE_VERSION)'

# Step 6: Install Angular dependencies
- script: |
    echo "Installing Angular dependencies"
    cd frontend
    npm install
  displayName: 'Install frontend dependencies'

# Step 7: Build the Angular frontend
- script: |
    echo "Building Angular frontend"
    cd frontend
    npm run build -- --prod
  displayName: 'Build frontend'

# Step 8: Publish frontend artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'frontend/dist'
    artifactName: 'frontend'
  displayName: 'Publish frontend artifact'
